version: '3.7'

services:
  logapp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/logapp
      - logapp_static_volume:/logapp/static
      - logapp_files_volume:/logapp/media
    restart: always
    ports:
      - "8000:8000"
    networks:
      - logapp_network
      
    depends_on:
      - logapp_postgresql
  logapp_postgresql:
    image: postgres:10
    container_name: logapp_postgresql
    volumes:
      - logapp_postgresql:/var/lib/postgresql/data
    restart: always
    env_file: .env
    ports:
      - "5432:5432"
    networks:
      - logapp_network
  
  
volumes:
  logapp_postgresql:
    external: true
  logapp_static_volume:
    external: true
  logapp_files_volume:
    external: true
  
networks:
  logapp_network:
    external: true
  nginx_network:
    external: true
  
