# Generated by Django 2.2 on 2022-02-26 00:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assign_to',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name2', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name3', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name4', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name5', models.CharField(blank=True, max_length=25, null=True, unique=True)),
                ('name6', models.CharField(blank=True, max_length=25, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('meli', 'Meli'), ('mellat', 'Mellat'), ('tejarat', 'Tejarat')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DownTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventDetailProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createduser+', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleteduser+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Incident_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PepolePresent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(blank=True, choices=[('arian', 'ARIAN'), ('amini', 'AMINI'), ('maroufi', 'MAROUFI')], max_length=10, null=True)),
                ('name3', models.CharField(blank=True, choices=[('arian', 'ARIAN'), ('amini', 'AMINI'), ('maroufi', 'MAROUFI')], max_length=10, null=True)),
                ('name4', models.CharField(blank=True, choices=[('arian', 'ARIAN'), ('amini', 'AMINI'), ('maroufi', 'MAROUFI')], max_length=10, null=True)),
                ('name5', models.CharField(blank=True, choices=[('arian', 'ARIAN'), ('amini', 'AMINI'), ('maroufi', 'MAROUFI')], max_length=10, null=True)),
                ('name6', models.CharField(blank=True, choices=[('arian', 'ARIAN'), ('amini', 'AMINI'), ('maroufi', 'MAROUFI')], max_length=10, null=True)),
                ('name7', models.CharField(blank=True, choices=[('arian', 'ARIAN'), ('amini', 'AMINI'), ('maroufi', 'MAROUFI')], max_length=10, null=True)),
                ('name8', models.CharField(blank=True, choices=[('arian', 'ARIAN'), ('amini', 'AMINI'), ('maroufi', 'MAROUFI')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report_To',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('bi', 'BI'), ('switch', 'SWITCH'), ('vpg', 'VPG')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='reson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='WAN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, choices=[('tehran', 'TEHRAN'), ('mashad', 'MASHAD')], max_length=20, null=True)),
                ('connection', models.CharField(blank=True, choices=[('mpls', 'MPLS'), ('E1', 'E1'), ('mobinnet', 'MOBINNET'), ('adsl', 'ADSL')], max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EventMainProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createduser+', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleteduser+', to=settings.AUTH_USER_MODEL)),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updateduser+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventKindofProblem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(blank=True, choices=[('open', 'OPEN'), ('in progress', 'IN PROGRESS'), ('close', 'CLOSE')], max_length=25, null=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('Start_time', models.TimeField()),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('description', models.TextField(max_length=255)),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='createduser+', to=settings.AUTH_USER_MODEL)),
                ('deleted_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deleteduser+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.EventDetailProblem')),
                ('updated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updateduser+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='event_image')),
                ('event', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='log.EventKindofProblem')),
            ],
        ),
        migrations.AddField(
            model_name='eventdetailproblem',
            name='problem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log.EventMainProblem'),
        ),
        migrations.AddField(
            model_name='eventdetailproblem',
            name='updated_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updateduser+', to=settings.AUTH_USER_MODEL),
        ),
    ]
