# Generated by Django 3.2.12 on 2022-04-24 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='day_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.day'),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='hour_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.hour'),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='minute_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.minute'),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='mounth_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.mounth'),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='year_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.year'),
        ),
    ]
