# Generated by Django 3.2.12 on 2022-03-13 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert1',
            new_name='Status_Of_Expert1',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert10',
            new_name='Status_Of_Expert10',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert11',
            new_name='Status_Of_Expert11',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert12',
            new_name='Status_Of_Expert12',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert2',
            new_name='Status_Of_Expert2',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert3',
            new_name='Status_Of_Expert3',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert4',
            new_name='Status_Of_Expert4',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert5',
            new_name='Status_Of_Expert5',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert6',
            new_name='Status_Of_Expert6',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert7',
            new_name='Status_Of_Expert7',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert8',
            new_name='Status_Of_Expert8',
        ),
        migrations.RenameField(
            model_name='eventkindofproblem',
            old_name='Staus_Of_Expert9',
            new_name='Status_Of_Expert9',
        ),
    ]
