# Generated by Django 3.2.12 on 2022-03-16 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_rename_city_city_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Assigng_to_others',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='auth.user+', to='log.other_organization'),
        ),
    ]
