# Generated by Django 3.2.12 on 2022-04-25 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0003_alter_eventkindofproblem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media'),
        ),
    ]
