# Generated by Django 3.2.12 on 2022-05-21 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0004_alter_eventkindofproblem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='status',
            field=models.CharField(blank=True, choices=[('open', 'OPEN'), ('in progress', 'IN PROGRESS'), ('close', 'CLOSE'), ('None', 'None')], max_length=25, null=True),
        ),
    ]
