# Generated by Django 3.2.12 on 2022-05-21 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0005_alter_eventkindofproblem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert1',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert10',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert11',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert12',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert2',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert3',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert4',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert5',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert6',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert7',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert8',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert9',
            field=models.CharField(blank=True, choices=[('present', 'PRESENT'), ('registrator', 'REGISTRATOR'), ('completor', 'COMPLETOR'), ('remote', 'REMOTE'), ('None', 'None')], max_length=25, null=True),
        ),
    ]
