# Generated by Django 3.2.12 on 2022-05-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0006_auto_20220521_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='Status_Of_problem',
            field=models.CharField(blank=True, choices=[('internal', 'INTERNAL'), ('external', 'EXTERNAL'), ('None', 'None')], max_length=10, null=True),
        ),
    ]
