# Generated by Django 3.2.12 on 2022-06-12 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0008_auto_20220521_1755'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert1',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert10',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert11',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert12',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert2',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert3',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert4',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert5',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert6',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert7',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert8',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Expert9',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert1',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert10',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert11',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert12',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert2',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert3',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert4',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert5',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert6',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert7',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert8',
        ),
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='Status_Of_Expert9',
        ),
    ]
