# Generated by Django 3.2.12 on 2022-06-12 17:17

from django.db import migrations, models
import log.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0009_auto_20220612_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media', validators=[log.models.validate_file_extension]),
        ),
    ]
