# Generated by Django 3.2.12 on 2022-06-12 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import log.models
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('log', '0011_alter_eventkindofproblem_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEventKindofProblem',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(blank=True, choices=[('open', 'OPEN'), ('in progress', 'IN PROGRESS'), ('close', 'CLOSE'), ('None', 'None')], max_length=25, null=True)),
                ('image', models.TextField(blank=True, max_length=100, null=True, validators=[log.models.validate_file_extension])),
                ('IncidentID', models.IntegerField(blank=True, null=True)),
                ('DownTime', models.CharField(blank=True, choices=[('no', 'NO'), ('yes', 'YES')], max_length=4, null=True)),
                ('SMS', models.CharField(blank=True, choices=[('sms', 'SMS'), ('nosms', 'NOSMS')], max_length=10, null=True)),
                ('description', models.TextField(max_length=255)),
                ('reson', models.TextField(max_length=255)),
                ('Status_Of_problem', models.CharField(blank=True, choices=[('internal', 'INTERNAL'), ('external', 'EXTERNAL'), ('None', 'None')], max_length=10, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('Assign_to_name1', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.assign_to')),
                ('Assign_to_name2', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.assign_to')),
                ('Assign_to_name3', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.assign_to')),
                ('Assign_to_name4', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.assign_to')),
                ('Assigng_to_others', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.other_organization')),
                ('Bank', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.bank')),
                ('Connection', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.connection')),
                ('ReportToDepartment', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.report_to')),
                ('city', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.city')),
                ('day_of_end', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.day')),
                ('day_of_start', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.day')),
                ('detailproblem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.eventdetailproblem')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('hour_of_end', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.hour')),
                ('hour_of_start', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.hour')),
                ('mainproblem', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.eventmainproblem')),
                ('minute_of_end', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.minute')),
                ('minute_of_start', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.minute')),
                ('mounth_of_end', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.mounth')),
                ('mounth_of_start', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.minute')),
                ('year_of_end', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.year')),
                ('year_of_start', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.year')),
            ],
            options={
                'verbose_name': 'historical event kindof problem',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
