# Generated by Django 3.2.12 on 2022-07-18 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0013_auto_20220718_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='mounth_of_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.mounth'),
        ),
        migrations.AlterField(
            model_name='historicaleventkindofproblem',
            name='mounth_of_start',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='log.mounth'),
        ),
    ]
