# Generated by Django 3.2.12 on 2022-07-18 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0014_auto_20220718_1606'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicaleventkindofproblem',
            name='name',
        ),
    ]
