# Generated by Django 3.2.12 on 2022-07-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0017_alter_mounth_mounth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='year',
            field=models.IntegerField(blank=True, max_length=300, null=True),
        ),
    ]
