# Generated by Django 3.2.12 on 2022-07-24 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0020_auto_20220724_2053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicaleventkindofproblem',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
