# Generated by Django 3.2.12 on 2022-07-24 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0021_auto_20220724_2058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventkindofproblem',
            name='name',
        ),
        migrations.RemoveField(
            model_name='historicaleventkindofproblem',
            name='name',
        ),
    ]
