# Generated by Django 3.2.12 on 2022-07-27 10:44

from django.db import migrations
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0024_auto_20220727_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventkindofproblem',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaleventkindofproblem',
            name='start_date',
            field=django_jalali.db.models.jDateTimeField(blank=True, null=True),
        ),
    ]
