# Generated by Django 3.2.12 on 2022-07-27 11:02

from django.db import migrations
import django.utils.timezone
import django_jalali.db.models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0025_auto_20220727_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventkindofproblem',
            name='start_date2',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaleventkindofproblem',
            name='start_date2',
            field=django_jalali.db.models.jDateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
