# Generated by Django 3.2.12 on 2022-07-31 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0036_alter_day_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='day',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
