# Generated by Django 3.2 on 2023-01-01 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0041_auto_20221210_1837'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e1mpls',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='e1mpls',
            name='name',
        ),
        migrations.RemoveField(
            model_name='e1mpls',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='e1mpls',
            name='status',
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='day_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.day'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='day_of_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.day'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='hour_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.hour'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='hour_of_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.hour'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='minute_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.minute'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='minute_of_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.minute'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='mounth_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.mounth'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='mounth_of_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.mounth'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='year_of_end',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.year'),
        ),
        migrations.AddField(
            model_name='e1mpls',
            name='year_of_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth.user+', to='log.year'),
        ),
    ]
