# Generated by Django 3.2 on 2023-02-17 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0043_auto_20230218_0213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventkindofproblem',
            name='year_of_start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log.year'),
        ),
    ]
